# Generated by Django 4.1.4 on 2022-12-14 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='command',
            new_name='comment',
        ),
    ]
